version: "3.9"

services:
  postgres:
    image: postgres:13
    container_name: postgres-poker-container
    env_file:
      - ./postgres/.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./data/postgres:/data/postgres
    networks:
      - gerneral_network

  api:
    build: ./poker_api/
    command: bundle exec rails s -b '0.0.0.0'
    depends_on:
      - postgres
    volumes:
      - ./poker_api:/poker_api
    ports:
      - "3000:3000"
    networks:
      - gerneral_network

  client:
    image: node:20
    container_name: poker_client
    working_dir: /app
    volumes:
      - ./poker_client:/app
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
    command: sh -c "npm install && npm run dev"
    networks:
      - gerneral_network

networks:
  gerneral_network:
    driver: bridge
